INSERT INTO baseType VALUES('DOCUMENT_DNI','TYPE_DOCUMENT','DNI','',null);
INSERT INTO baseType VALUES('DOCUMENT_LE','TYPE_DOCUMENT','LE','',null);
INSERT INTO baseType VALUES('DOCUMENT_PAST','TYPE_DOCUMENT','Pasaporte','',null);
INSERT INTO baseType VALUES('DOCUMENT_C_EXTRA','TYPE_DOCUMENT','Carne de extrangeria','',null);

INSERT INTO baseType VALUES('PERSON_ACT','STATUS_PERSON','Activo','',null);
INSERT INTO baseType VALUES('PERSON_INACT','STATUS_PERSON','Inactivo','',null);

INSERT INTO baseType VALUES('USER_ACT','STATUS_USER','Activo','',null);
INSERT INTO baseType VALUES('USER_INACT','STATUS_USER','Inactivo','',null);

INSERT INTO baseType VALUES('HOTEL_ACT','STATUS_HOTEL','Activo','',NULL);
INSERT INTO baseType VALUES('HOTEL_INACT','STATUS_HOTEL','Inactivo','',NULL);

INSERT INTO baseType VALUES('PRODUCT_ACT','STATUS_PRODUCT','Activo','',NULL);
INSERT INTO baseType VALUES('PRODUCT_INACT','STATUS_PRODUCT','Inactivo','',NULL);

INSERT INTO baseType VALUES('ENTERPRICE_ACT','STATUS_ENTERPRICE','Activo','',NULL);
INSERT INTO baseType VALUES('ENTERPRICE_INACT','STATUS_ENTERPRICE','Inactivo','',NULL);